name 'ghoneycutt-cve'
version '0.1.0'
source 'git://github.com/ghoneycutt/puppet-module-cve.git'
author 'ghoneycutt'
license 'Apache 2.0'
summary 'Check for CVEs'
description 'Puppet module to list CVEs'
project_page 'https://github.com/ghoneycutt/puppet-module-cve'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
